### PR TITLE
Adding Tests to Twigify

### PR DESCRIPTION
**Pull request by scottwarren**
Currently a WIP, but would like to re-integrate sooner rather than later.

I will consider this a success when the test coverage is higher than what it is. Currently it is: 
## Coverage summary

Statements   : 60% ( 18/30 )
Branches     : 50% ( 1/2 )
Functions    : 40% ( 2/5 )
Lines        : 58.62% ( 17/29 )

---

I have also added a Travis CI base so you can run the build on Travis (you will need to make an account and link it)

I added a readme with this PR as well.

### CODE REVIEW

**Comment by dane-harnett** [comment]
Looking good, might have to make some changes to this as I have realised that my code won't work with embedded includes. I think a change to the twig core is going to be required.

**Comment by scottwarren** [comment]
No worries. When you do I can merge it in :-)

**Comment by scottwarren** [comment]
might have to look at https://github.com/zertosh/jstify/blob/master/test/test.js to improve tests

**Comment by scottwarren** [comment]
with PR's incoming, it'd be good to revive this @dane-harnett, what do you think?

**Comment by dane-harnett** [comment]
@scottwarren Unfortunately I don't think it's worth my time, browserify seems to have lost to webpack, and twigjs seems to have lost to react. I know people might be wanting to use this in the mean time or with legacy systems happy for you to merge the PR's or add more collaborators if they really want it.

**Comment by scottwarren** [comment]
@dane-harnett fair enough - likely will need to merge #9 to fix #8

**Pull request closed without merging**
